services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/franchise-backend:latest
    container_name: franchise-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul      
      - PORT=5000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CORS_ORIGIN=${CORS_ORIGIN}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:5000/api/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    networks:
      - franchise-network

networks:
  franchise-network:
    external: true
